[package]
name = "doay-web"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
mime_guess = "2"
include_dir = "0.7"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
